app:
  name: "Newbie Ecommerce"
  port: ":4000"

db:
  host: "103.193.176.215"
  port: "5432"
  user: "postgres"
  password: "74712331"
  name: "newbie-ecommerce"

redis:
  host: "localhost"
  port: "6377"
  password: ""
  lifeTime: 24

meili:
  host: "http://localhost:7700"
  key: "ThisIsMasterKey"

jwt:
  key: "secret"

cloudinary:
  name: "zazhil-cloudinary"
  apiKey: "914726226983175"
  apiSecret: "cPSCFEY3kzElZNlOjXqwtdP8-6M"
